#lang racket
(display "Digite la base del romboide")
(define bR (read))
(newline)
(display "Digite la altura del romboide")
(newline)
(define hR (read))
(define PerimetroR (+ (* 2 bR )(* 2 hR)))
(define AreaR (* bR hR ))
(display "Digite la Base Mayor del Trapecio")
(define BT (read))
(newline)
(display "Digite la base menor del Trapecio")
(newline)
(define bT (read))
(display "Digite la altura")
(newline)
(define hT (read))
(display "Digite el valor del lado lateral derecho ")
(newline)
(define aDT (read))
(display "Digite el valor del lado lateral izquierdo ")
(define aIT (read))
(newline)
(display "Digite el valor del radio del circulo ")
(define rC (read))
(newline)
(display "Digite el valor de la longitud del circulo ")
(define lC (read))
(define PerimetroC (round (* 2 pi rC) ))
(define AreaC (round (* pi (sqr rC)) ))
(define PerimetroT (+ aIT aDT BT bT))
(define AreaT (* bT hT ))
(define PI 3.14)
(display "---------------------------------------------------------------------------------")
(newline)
(displayln "\tTABLA DE FIGURAS\t")
(display "---------------------------------------------------------------------------------")
(newline)
(displayln "|\tFiguras\t\t|\tDatos\t|\tPerimetro\t|\tArea\t|") 
(display "---------------------------------------------------------------------------------")
(newline)
(display "|\tRomboide\t|")
(display "B = ")
(display bR)
(display "\t\t|")
(display"P = ")
(display PerimetroR)
(display "\t\t\t|")
(display" A = ")
(display AreaR)
(display "\t|")
(newline)
(display "|\t\t\t|")
(display "h = ")
(display hR)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "---------------------------------------------------------------------------------")
(newline)
(display "|\tTrapecio\t|")
(display "B = ")
(display BT)
(display "\t\t|")
(display"P = ")
(display PerimetroT)
(display "\t\t\t|")
(display" A = ")
(display AreaT)
(display "\t|")
(newline)
(display "|\t\t\t|")
(display "b = ")
(display bR)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "|\t\t\t|")
(display "h = ")
(display hT)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "|\t\t\t|")
(display "a = ")
(display aDT)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "|\t\t\t|")
(display "d = ")
(display aIT)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "---------------------------------------------------------------------------------")
(newline)
(display "|\tCirculo\t\t|")
(display "PI = ")
(display  PI)
(display "\t|")
(display"P = ")
(display PerimetroC)
(display "\t\t|")
(display" A = ")
(display AreaC)
(display "\t|")
(newline)
(display "|\t\t\t|")
(display "r = ")
(display rC)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "|\t\t\t|")
(display "L = ")
(display lC)
(display "\t\t|")
(display "\t\t\t|")
(display "\t\t|")
(newline)
(display "---------------------------------------------------------------------------------")
(newline)
