#lang racket
;El usario digita los valores
(display "Digite el Tiempo del cuerpo 1")
(define TiempoCuerpo1 (read))
(display "Digite el Espacio del cuerpo 1")
(define EspacioCuerpo1 (read))
(display "Digite el Tiempo del cuerpo 2")
(define TiempoCuerpo2 (read))
(display "Digite el Espacio del cuerpo 2")
(define EspacioCuerpo2 (read))
(display "Digite el Tiempo del cuerpo 3")
(define TiempoCuerpo3 (read))
(display "Digite el Espacio del cuerpo 3")
(define EspacioCuerpo3 (read))
(define VelocidadCuerpo1 (/ EspacioCuerpo1 TiempoCuerpo1))
(define VelocidadCuerpo2 (/ EspacioCuerpo2 TiempoCuerpo2))
(define VelocidadCuerpo3 (/ EspacioCuerpo3 TiempoCuerpo3))
(define PromedioDeDistancia (/ (+ EspacioCuerpo1  EspacioCuerpo2  EspacioCuerpo3)3))
(define PromedioDeTiempo (/ (+ TiempoCuerpo1  TiempoCuerpo2  TiempoCuerpo3)3))
(define PromedioDeVelocidad (/ (+ VelocidadCuerpo1 VelocidadCuerpo2 VelocidadCuerpo3) 3))
; Distacia = velocidad *tiempo
; Velocidad = distancia/tiempo
(display "+------------------------------------------------------------------+")
(newline)
(display "|\t\t|\tC1\t|\tC2\t|\tC3\t|\tPRO\t|")
(newline)
(display "+------------------------------------------------------------------+")
(newline)
(display "|\tDistancia\t|")
(display EspacioCuerpo1)
(display "\t|")
(display EspacioCuerpo2)
(display "\t|")
(display EspacioCuerpo3)
(display "\t|")
(display PromedioDeDistancia)
(display "\t|")
(newline)
(display "+------------------------------------------------------------------+")
(newline)
(display "|\tVelocidad\t|")
(display VelocidadCuerpo1)
(display "\t|")
(display VelocidadCuerpo2)
(display "\t|")
(display VelocidadCuerpo3)
(display "\t|")
(display PromedioDeVelocidad)
(display "\t|")
(newline)
(display "+------------------------------------------------------------------+")
(newline)
(display "|\tTIEMPO\t|")
(display TiempoCuerpo1)
(display "\t|")
(display TiempoCuerpo2)
(display "\t|")
(display TiempoCuerpo3)
(display "\t|")
(display PromedioDeTiempo)
(display "\t|")
(newline)
(display "+------------------------------------------------------------------+")