;El usario digita los valores
#lang racket
;El usario digita los valores
(display "Digite el Tiempo del cuerpo 1")
(define TiempoCuerpo1 (read))
(display "Digite el Espacio del cuerpo 1")
(define EspacioCuerpo1 (read))
(display "Digite el Tiempo del cuerpo 2")
(define TiempoCuerpo2 (read))
(display "Digite el Espacio del cuerpo 2")
(define EspacioCuerpo2 (read))
(display "Digite el Tiempo del cuerpo 3")
(define TiempoCuerpo3 (read))
(display "Digite el Espacio del cuerpo 3")
(define EspacioCuerpo3 (read))
(define VelocidadCuerpo1 (/ EspacioCuerpo1 TiempoCuerpo1))
(define VelocidadCuerpo2 (/ EspacioCuerpo2 TiempoCuerpo2))
(define VelocidadCuerpo3 (/ EspacioCuerpo3 TiempoCuerpo3))
(define Promedio de veloc)
; Distacia = velocidad *tiempo
; Velocidad = distancia/tiempo
(display "+------------------------------------------------------------------+")
(newline)
(display "|\t\t|\tC1\t|\tC2\t|\tC3\t|\tPRO\t|")
(newline)
(display "+------------------------------------------------------------------+")
(newline)
(display "|\tDistancia\t|")
(display EspacioCuerpo1)
(display "\t|")
(display EspacioCuerpo2)
(display "\t|")
(display EspacioCuerpo3)
(display "\t|")
