#lang racket

; El usuario digita los valores de Tiempo y Espacio para cada uno de los cuerpos
(display "Digite el Tiempo del cuerpo 1")
(define TiempoCuerpo1 (read))
(display "Digite el Espacio del cuerpo 1")
(define EspacioCuerpo1 (read))
(display "Digite el Tiempo del cuerpo 2")
(define TiempoCuerpo2 (read))
(display "Digite el Espacio del cuerpo 2")
(define EspacioCuerpo2 (read))
(display "Digite el Tiempo del cuerpo 3")
(define TiempoCuerpo3 (read))
(display "Digite el Espacio del cuerpo 3")
(define EspacioCuerpo3 (read))

; Se calcula la velocidad de cada cuerpo dividiendo la distancia recorrida entre el tiempo empleado
(define VelocidadCuerpo1 (/ EspacioCuerpo1 TiempoCuerpo1))
(define VelocidadCuerpo2 (/ EspacioCuerpo2 TiempoCuerpo2))
(define VelocidadCuerpo3 (/ EspacioCuerpo3 TiempoCuerpo3))

; Se calcula el promedio de la distancia, el tiempo y la velocidad de los tres cuerpos
(define PromedioDeDistancia (/ (+ EspacioCuerpo1 EspacioCuerpo2 EspacioCuerpo3) 3))
(define PromedioDeTiempo (/ (+ TiempoCuerpo1 TiempoCuerpo2 TiempoCuerpo3) 3))
(define PromedioDeVelocidad (/ (+ VelocidadCuerpo1 VelocidadCuerpo2 VelocidadCuerpo3) 3))

; Se imprimen los resultados de la tabla
(display "+-----------------------------------------------------------------------------------------+\n")
(display "|\t\t\t|\tC1\t|\tC2\t|\tC3\t|\tPRO\t|\n")
(display "+-----------------------------------------------------------------------------------------+\n")
(display "|\tDistancia\t|\t")
(display EspacioCuerpo1)
(display "\t|\t")
(display EspacioCuerpo2)
(display "\t|\t")
(display EspacioCuerpo3)
(display "\t|\t")
(display PromedioDeDistancia)
(display "\t|\n")
(display "+-----------------------------------------------------------------------------------------+\n")
(display "|\tVelocidad\t|\t")
(display VelocidadCuerpo1)
(display "\t|\t")
(display VelocidadCuerpo2)
(display "\t|\t")
(display VelocidadCuerpo3)
(display "\t|\t")
(display PromedioDeVelocidad)
(display "\t|\n")
(display "+-----------------------------------------------------------------------------------------+\n")
(display "|\tTiempo\t\t|\t")
(display TiempoCuerpo1)
(display "\t|\t")
(display TiempoCuerpo2)
(display "\t|\t")
(display TiempoCuerpo3)
(display "\t|\t")
(display PromedioDeTiempo)
(display "\t\t|\n")
(display "+-----------------------------------------------------------------------------------------+\n")

; La tabla muestra la distancia, velocidad y tiempo de cada cuerpo, así como los promedios de cada variable en la columna PRO.